language: android

addons:
  ssh_known_hosts:
  - git.epitech.eu

android:
  components:
  - build-tools-28.0.3
  - android-28

before_install:
  - openssl aes-256-cbc -K $encrypted_ead2ccba5de1_key -iv $encrypted_ead2ccba5de1_iv -in id_rsa.enc -out id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./id_rsa
  - ssh-add ./id_rsa

script:
  - "./gradlew build"

after_success:
  - git remote add deploy git@github.com:bguillaumat/Epicture.git
  - git push deploy --all